shell = "zsh"

[window]
opacity = 0.65

[cursor]
style = { shape = "Beam", blinking = "On" }

[font]
normal = {family = "Meslo LGS NF" }
size = 12

[colors.primary]
background = '#24292e'
foreground = '#d1d5da'

[colors.normal]
black   = '#586069'
red     = '#ea4a5a'
green   = '#34d058'
yellow  = '#ffea7f'
blue    = '#2188ff'
magenta = '#b392f0'
cyan    = '#39c5cf'
white   = '#d1d5da'

[colors.bright]
black   = '#959da5'
red     = '#f97583'
green   = '#85e89d'
yellow  = '#ffea7f'
blue    = '#79b8ff'
magenta = '#b392f0'
cyan    = '#56d4dd'
white   = '#fafbfc'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#f97583'
