# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  #services.fprintd.enable = true;
  #security.pam.services.sudo.fprintAuth = true;
  #security.pam.services.sddm.fprintAuth = true;
  #security.pam.services.login.fprintAuth = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fa1cb455-26b9-45aa-8bdb-bae9f72e8edb";
      fsType = "ext4";
    };

  # Boot
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";
  boot.loader.grub.useOSProber = true;
  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = null;
  };
  boot.loader.grub.enableCryptodisk=true;
  boot.initrd.luks.devices."luks-475a682c-bb98-4d6d-8c41-a0787f80b626".keyFile = "/crypto_keyfile.bin";
  # Enable swap on luks
  boot.initrd.luks.devices."luks-e55999bd-de2e-4f76-a992-cdc7d8849e56".device = "/dev/disk/by-uuid/e55999bd-de2e-4f76-a992-cdc7d8849e56";
  boot.initrd.luks.devices."luks-e55999bd-de2e-4f76-a992-cdc7d8849e56".keyFile = "/crypto_keyfile.bin";
  boot.initrd.luks.devices."luks-475a682c-bb98-4d6d-8c41-a0787f80b626".device = "/dev/disk/by-uuid/475a682c-bb98-4d6d-8c41-a0787f80b626";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/dab732eb-edf8-4d19-ad54-c600460dfb91"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
