alias ls="ls --color=auto"
alias l="ls -lah --color=auto"
alias la="ls -ah --color=auto"
alias ll="ls -lh --color=auto"
alias aptup="sudo aptitude update && sudo aptitude full-upgrade"
alias flatup="sudo flatpak update"
alias sizeof="du -sh"
alias x11vncUnencrypted="x11vnc -auth guess -forever -loop -noxdamage -repeat -rfbauth /home/simon/.vnc/passwd -rfbport 5900 -shared"
alias x11vncEncrypted="x11vnc -auth guess -forever -loop -noxdamage -repeat -rfbauth /home/simon/.vnc/passwd -rfbport 5900 -shared -ssl"
