tabs 4 # Set tab width to 4
set -k # Enable comments
clear

__git_files () {
    _wanted files expl 'local files' _files
}

source ~/dotfiles/scripts/zsh/prompt.zsh # Prompt
source ~/dotfiles/scripts/zsh/autocomplete.zsh # Autocomplete
source ~/dotfiles/scripts/zsh/plugins.zsh # Plugins
source ~/dotfiles/scripts/zsh/aliases.zsh # Aliases
source ~/dotfiles/scripts/zsh/path.zsh # Path
#source ~/dotfiles/scripts/zsh/locale.zsh # Locale
source ~/dotfiles/scripts/zsh/keybindings.zsh # Keybindings
source ~/dotfiles/scripts/zsh/history.zsh # History
#source ~/dotfiles/scripts/zsh/nvm.zsh # NVM
source ~/dotfiles/scripts/zsh/env.zsh # Variables
#source ~/dotfiles/scripts/zsh/kdesrc.zsh # KDE SRC

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#fastfetch # Run fastfetch
