words = [
    "barcode",
    "functors",
    "homogenity",
    "linters",
    "monoidal",
    "morphisms",
    "omp",
    "unital",
]
ignore_paths = [
    "**/*.typ",
    "**/*.md",
    "**/*.tex",
    "**/*.txt",
]
