"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = "<Esc>", run = "close" },
  { on = "M", run = "plugin mount", desc = "Mount" },
  { on = "l", run = "plugin smart-enter", desc = "Smart enter" },
  { on = "<Enter>", run = "plugin smart-enter", desc = "Smart enter" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = [
    "g",
    "r",
  ], run = "cd /", desc = "Go /" },
]
